framework:
    default_locale: en
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en
        providers:
L'adresse e-mail '{{ value }}' n'est pas valide.: "L'adresse e-mail '{{ value }}' n'est pas valide. Veuillez entrer une adresse e-mail valide."
