vich_uploader:
    db_driver: orm

    mappings:
        user:
            uri_prefix: /images/user
            upload_destination: '%kernel.project_dir%/public/images/user'
            namer: vich\UploaderBundle\Naming\UniqidNamer
            # Ajoutez d'autres options de configuration si nécessaire
