vich_uploader:
    db_driver: orm

    mappings:
        user_images:
             uri_prefix: /images/users
             upload_destination: '%kernel.project_dir%/public/images/users'   
             namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
             delete_on_remove: true
             delete_on_update: true