controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
home:
    path: /
    controller: App\Controller\HomeController::index
error_404:
    path: /{_locale}/error404
    controller: App\Controller\ErrorController::notFound
   